### ISSUE TITLE
Mail closing connection  with Unexpectedly Closed error

### ISSUE THREAD

**Issue by Sweetdaddy** [ccrisan/motionpie#242]
Thank you for looking.  I'm having an issue from notification.  The mail is starting, but ends with an Unexpectedly Closed error.  The password is in clear text, and it has special characters.  Could that be causing an issue?

1] [DBG] [EVT] exec_command: Executing external command '/programs/motioneye/eventrelay.py start 1; /programs/motioneye/sendmail.py "smtp.mail.yahoo.com" "465" "******@******.com" "*******" "True" "******@******.com" "motion_start" "1" "2015-07-17T13:50:18" "15"'

2015-07-17 13:51:36: ERROR: failed to send mar: Connection unexpectedly closed: timed out
Traceback (most recent call last):
  File "/programs/motioneye/sendmail.py", line 182, in on_message
    send_mail(server, port, account, password, tls, to, subject, message, files)
  File "/programs/motioneye/sendmail.py", line 57, in send_mail
    conn = smtplib.SMTP(server, port, timeout=getattr(settings, 'SMTP_TIMEOUT', 60))
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
  File "/usr/lib/python2.7/smtplib.py", line 317, in connect
  File "/usr/lib/python2.7/smtplib.py", line 365, in getreply
SMTPServerDisconnected: Connection unexpectedly closed: timed out

**Comment by ccrisan** [comment]
Your SMTP server does not respond with 60 seconds. It could either be a (temporary) server fault or a local connectivity problem (e.g. connections on port 465 are not allowed by your firewall).
