### ISSUE TITLE
Adding a 3rdcam

### ISSUE THREAD

**Issue by drknstrmyknight** [ccrisan/motionpie#278]
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 3.18.12-quick (ccrisan@supermicro) (gcc version 4.8.4 (Buildroot 2015.08-git-g73e1681) ) #1 PREEMPT Sun Jul 19 19:51:43 EEST 2015
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] Machine: BCM2708
[    0.000000] Memory policy: Data cache writeback
[    0.000000] On node 0 totalpages: 98304
[    0.000000] free_area_init_node: node 0, pgdat c0515b48, node_mem_map d7cf8000
[    0.000000]   Normal zone: 768 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 98304 pages, LIFO batch:31
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 97536
[    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708.boardrev=0xe bcm2708.serial=0xb41cc420 smsc95xx.macaddr=B8:27:EB:1C:C4:20 bcm2708_fb.fbswap=1 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.fiq_fix_enable=1 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 rootwait ro rootflags=noload
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 384156K/393216K available (4159K kernel code, 201K rwdata, 688K rodata, 128K init, 328K bss, 9060K reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xffe00000   (2048 kB)
                   vmalloc : 0xd8800000 - 0xff000000   ( 616 MB)
                   lowmem  : 0xc0000000 - 0xd8000000   ( 384 MB)
                   modules : 0xbf000000 - 0xc0000000   (  16 MB)
                     .text : 0xc0008000 - 0xc04c3f0c   (4848 kB)
                     .init : 0xc04c4000 - 0xc04e4000   ( 128 kB)
                     .data : 0xc04e4000 - 0xc0516580   ( 202 kB)
                      .bss : 0xc0516580 - 0xc0568824   ( 329 kB)
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:522
[    0.000021] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483648000ns
[    0.000068] Switching to timer-based delay loop, resolution 1000ns
[    0.000634] Console: colour dummy device 80x30
[    0.001491] console [tty1] enabled
[    0.001536] Calibrating delay loop (skipped), value calculated using timer frequency.. 2.00 BogoMIPS (lpj=1000)
[    0.001600] pid_max: default: 32768 minimum: 301
[    0.001927] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.001983] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.002915] CPU: Testing write buffer coherency: ok
[    0.003369] Setting up static identity map for 0x415de8 - 0x415e20
[    0.005397] devtmpfs: initialized
[    0.022172] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.023154] NET: Registered protocol family 16
[    0.028310] DMA: preallocated 4096 KiB pool for atomic coherent allocations
[    0.029310] bcm2708.uart_clock = 3000000
[    0.031012] mailbox: Broadcom VideoCore Mailbox driver
[    0.031158] bcm2708_vcio: mailbox at f200b880
[    0.031533] bcm_power: Broadcom power driver
[    0.031583] bcm_power_open() -> 0
[    0.031613] bcm_power_request(0, 8)
[    0.532305] bcm_mailbox_read -> 00000080, 0
[    0.532348] bcm_power_request -> 0
[    0.532548] Serial: AMBA PL011 UART driver
[    0.532735] dev:f1: ttyAMA0 at MMIO 0x20201000 (irq = 83, base_baud = 0) is a PL011 rev3
[    0.568689] usbcore: registered new interface driver usbfs
[    0.568868] usbcore: registered new interface driver hub
[    0.568997] usbcore: registered new device driver usb
[    0.569111] media: Linux media interface: v0.10
[    0.569299] Linux video capture interface: v2.00
[    0.570983] cfg80211: Calling CRDA to update world regulatory domain
[    0.571724] Switched to clocksource stc
[    0.572157] FS-Cache: Loaded
[    0.572525] CacheFiles: Loaded
[    0.586337] NET: Registered protocol family 2
[    0.587595] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.587794] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.587927] TCP: Hash tables configured (established 4096 bind 4096)
[    0.588038] TCP: reno registered
[    0.588084] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.588143] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.588449] NET: Registered protocol family 1
[    0.589910] bcm2708_dma: DMA manager at f2007000
[    0.590094] bcm2708_gpio: bcm2708_gpio_probe c04efe80
[    0.590449] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    0.591570] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.593860] msgmni has been set to 750
[    0.596374] io scheduler noop registered
[    0.596436] io scheduler deadline registered
[    0.596485] io scheduler cfq registered (default)
[    0.596879] BCM2708FB: allocated DMA memory 57960000
[    0.596960] BCM2708FB: allocated DMA channel 0 @ f2007000
[    0.602116] Console: switching to colour frame buffer device 82x26
[    0.608294] bcm2708-dmaengine bcm2708-dmaengine: Load BCM2835 DMA engine driver
[    0.610827] uart-pl011 dev:f1: no DMA platform data
[    0.613465] bcm2708_rng_init=d8c1a000
[    1.531214] brd: module loaded
[    1.533641] vchiq: vchiq_init_state: slot_zero = 0xd8804000, is_master = 0
[    1.536536] PPP generic driver version 2.4.2
[    1.539409] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.742044] Core Release: 2.80a
[    1.744194] Setting default values for core params
[    1.746276] Finished setting default values for core params
[    1.948458] Using Buffer DMA mode
[    1.950502] Periodic Transfer Interrupt Enhancement - disabled
[    1.952533] Multiprocessor Interrupt Enhancement - disabled
[    1.954542] OTG VER PARAM: 0, OTG VER FLAG: 0
[    1.956545] Dedicated Tx FIFOs mode
[    1.958844] WARN::dwc_otg_hcd_init:1047: FIQ DMA bounce buffers: virt = 0xd8c22000 dma = 0x5798c000 len=9024
[    1.962870] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
[    1.970474] dwc_otg: Microframe scheduler enabled
[    1.970536] WARN::hcd_init_fiq:412: FIQ on core 0 at 0xc02a90b8
[    1.972536] WARN::hcd_init_fiq:413: FIQ ASM at 0xc02a9390 length 36
[    1.974519] WARN::hcd_init_fiq:438: MPHI regs_base at 0xd8c1c000
[    1.976580] dwc_otg bcm2708_usb: DWC OTG Controller
[    1.978660] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
[    1.980792] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
[    1.982814] Init: Port Power? op_state=1
[    1.984785] Init: Power Port (0)
[    1.986993] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    1.989022] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.991006] usb usb1: Product: DWC OTG Controller
[    1.992963] usb usb1: Manufacturer: Linux 3.18.12-quick dwc_otg_hcd
[    1.994933] usb usb1: SerialNumber: bcm2708_usb
[    1.997964] hub 1-0:1.0: USB hub found
[    2.000043] hub 1-0:1.0: 1 port detected
[    2.002485] dwc_otg: FIQ enabled
[    2.002506] dwc_otg: NAK holdoff enabled
[    2.002517] dwc_otg: FIQ split-transaction FSM enabled
[    2.002543] Module dwc_common_port init
[    2.002812] uvcvideo: Unable to create debugfs directory
[    2.004973] usbcore: registered new interface driver uvcvideo
[    2.006906] USB Video Class driver (1.1.1)
[    2.009509] bcm2708 watchdog, heartbeat=10 sec (nowayout=0)
[    2.011654] bcm2835-cpufreq: min=700000 max=700000
[    2.014039] sdhci: Secure Digital Host Controller Interface driver
[    2.015964] sdhci: Copyright(c) Pierre Ossman
[    2.018018] DMA channels allocated for the MMC driver
[    2.039754] Load BCM2835 MMC driver
[    2.043690] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.045967] hidraw: raw HID events driver (C) Jiri Kosina
[    2.049293] usbcore: registered new interface driver usbhid
[    2.052471] usbhid: USB HID core driver
[    2.054933] ip_tables: (C) 2000-2006 Netfilter Core Team
[    2.057133] TCP: cubic registered
[    2.059142] NET: Registered protocol family 17
[    2.061268] Key type dns_resolver registered
[    2.074336] Waiting for root device /dev/mmcblk0p2...
[    2.098387] mmc0: host does not support reading read-only switch, assuming write-enable
[    2.104873] mmc0: new high speed SDHC card at address 0002
[    2.107396] mmcblk0: mmc0:0002 00000 7.32 GiB 
[    2.110915]  mmcblk0: p1 p2 p3
[    2.182349] EXT4-fs (mmcblk0p2): mounted filesystem without journal. Opts: noload
[    2.186624] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    2.192849] devtmpfs: mounted
[    2.195651] Freeing unused kernel memory: 128K (c04c4000 - c04e4000)
[    2.202083] Indeed it is in host mode hprt0 = 00021501
[    2.373938] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.376554] Indeed it is in host mode hprt0 = 00001101
[    2.563246] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    2.565762] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.571931] hub 1-1:1.0: USB hub found
[    2.575822] hub 1-1:1.0: 5 ports detected
[    2.625834] bcm2835-v4l2: scene mode selected 0, was 0
[    2.626397] bcm2835-v4l2: V4L2 device registered as video0 - stills mode > 2592x1944
[    2.636069] bcm2835-v4l2: Broadcom 2835 MMAL video capture ver 0.0.2 loaded.
[    2.856053] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.945247] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    2.949400] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.085596] udevd[82]: starting version 3.0
[    3.107373] random: udevd urandom read with 110 bits of entropy available
[    3.131685] udevd[82]: specified group 'input' unknown
[    3.499985] bcm2708_i2c_init_pinmode(1,2)
[    3.514451] bcm2708_i2c_init_pinmode(1,3)
[    3.531900] bcm2708_i2c bcm2708_i2c.1: BSC1 Controller at 0x20804000 (irq 79) (baudrate 100000)
[    3.612096] smsc95xx v1.0.4
[    3.688421] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:1c:c4:20
[    3.724346] usbcore: registered new interface driver smsc95xx
[    3.817110] random: nonblocking pool is initialized
[   32.121438] EXT4-fs (mmcblk0p3): mounted filesystem with ordered data mode. Opts: (null)
[   33.024690] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   34.572631] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
[  236.805817] bcm2835-v4l2: error 0 waiting for frame completion
[  259.884829] bcm2835-v4l2: error 0 waiting for frame completion
[336524.817838] bcm2835-v4l2: error 0 waiting for frame completion

**Comment by drknstrmyknight** [comment]
Blanked the password from the 3rd cam, and when I added it it blew out the local camera and the remote that was working.
2015-08-24 13:41:52: INFO: hello! this is motionPie 20150719
2015-08-24 13:41:52: INFO: main config file /data/etc/motion.conf does not exist, using default values
2015-08-24 13:41:53: INFO: cleanup started
2015-08-24 13:41:53: INFO: wsswitch started
2015-08-24 13:41:53: INFO: thumbnailer started
2015-08-24 13:41:54: INFO: server started
2015-08-24 13:41:55: INFO: adding new camera with id 1...
2015-08-24 13:41:56: INFO: main config file /data/etc/motion.conf does not exist, using default values
2015-08-24 13:41:58: WARNING: control hue not found for device /dev/video0
2015-08-24 13:43:31: WARNING: 404 HEAD /robots.txt (192.168.111.100) 29.01ms
2015-08-24 13:44:03: WARNING: control hue not found for device /dev/video0
2015-08-24 13:44:03: WARNING: control hue not found for device /dev/video0
2015-08-24 13:44:03: WARNING: control hue not found for device /dev/video0
2015-08-24 13:44:48: WARNING: control hue not found for device /dev/video0
2015-08-24 13:44:48: WARNING: control hue not found for device /dev/video0
2015-08-24 13:45:12: WARNING: control hue not found for device /dev/video0
2015-08-24 13:45:12: WARNING: control hue not found for device /dev/video0
2015-08-24 13:59:36: WARNING: control hue not found for device /dev/video0
2015-08-24 13:59:36: WARNING: control hue not found for device /dev/video0
2015-08-24 13:59:36: WARNING: control hue not found for device /dev/video0
2015-08-24 16:17:30: WARNING: 404 HEAD /robots.txt (192.168.111.100) 28.27ms
2015-08-24 19:41:34: WARNING: 404 HEAD /robots.txt (192.168.111.100) 30.71ms
2015-08-24 19:48:53: WARNING: 404 HEAD /robots.txt (192.168.111.100) 58.40ms
2015-08-24 20:52:01: WARNING: 404 HEAD /robots.txt (192.168.111.100) 27.49ms
2015-08-26 22:09:30: WARNING: control hue not found for device /dev/video0
2015-08-26 22:10:22: WARNING: control hue not found for device /dev/video0
2015-08-26 22:10:27: WARNING: control hue not found for device /dev/video0
2015-08-26 22:10:28: WARNING: control hue not found for device /dev/video0
2015-08-26 22:10:28: WARNING: control hue not found for device /dev/video0
2015-08-26 22:10:28: WARNING: control hue not found for device /dev/video0
2015-08-27 06:20:32: WARNING: control hue not found for device /dev/video0
2015-08-27 10:24:38: WARNING: control hue not found for device /dev/video0
2015-08-27 10:24:39: WARNING: control hue not found for device /dev/video0
2015-08-27 10:24:39: WARNING: control hue not found for device /dev/video0
2015-08-27 10:26:36: WARNING: control hue not found for device /dev/video0
2015-08-27 10:26:39: WARNING: 404 HEAD /robots.txt (192.168.111.100) 27.55ms
2015-08-27 11:27:45: WARNING: 404 HEAD /robots.txt (192.168.111.100) 61.20ms
2015-08-27 21:25:33: WARNING: 404 HEAD /robots.txt (192.168.111.100) 27.66ms
2015-08-27 21:27:33: WARNING: 404 HEAD /robots.txt (192.168.111.100) 27.71ms
2015-08-27 21:47:47: WARNING: 404 HEAD /robots.txt (192.168.111.100) 60.09ms
2015-08-27 21:48:02: WARNING: 404 HEAD /robots.txt (192.168.111.100) 27.55ms
2015-08-27 21:48:14: WARNING: 404 HEAD /robots.txt (192.168.111.100) 27.58ms
2015-08-27 21:50:14: WARNING: 404 HEAD /robots.txt (192.168.111.100) 27.67ms
2015-08-27 21:50:27: WARNING: 404 HEAD /robots.txt (192.168.111.100) 43.03ms
2015-08-27 21:50:45: WARNING: 404 HEAD /robots.txt (192.168.111.100) 57.50ms
2015-08-27 21:52:28: WARNING: control hue not found for device /dev/video0
2015-08-27 22:10:00: WARNING: error on read
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/iostream.py", line 630, in _handle_read
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/iostream.py", line 600, in _read_to_buffer_loop
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/iostream.py", line 712, in _read_to_buffer
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/iostream.py", line 976, in read_from_fd
error: [Errno 113] No route to host
2015-08-27 22:10:00: ERROR: Uncaught exception
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/http1connection.py", line 691, in _server_request_loop
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/gen.py", line 810, in run
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/http1connection.py", line 166, in _read_message
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
  File "<string>", line 3, in raise_exc_info
error: [Errno 113] No route to host
2015-08-27 22:59:00: WARNING: 404 HEAD /robots.txt (192.168.111.100) 28.20ms
2015-08-27 22:59:39: WARNING: 404 HEAD /robots.txt (192.168.111.100) 37.39ms
2015-08-27 23:00:07: WARNING: 404 HEAD /robots.txt (192.168.111.100) 55.72ms
2015-08-28 10:28:21: WARNING: 404 HEAD /robots.txt (192.168.111.100) 34.65ms
2015-08-28 11:09:30: WARNING: control hue not found for device /dev/video0
2015-08-28 11:09:30: WARNING: control hue not found for device /dev/video0
2015-08-28 11:18:39: WARNING: control hue not found for device /dev/video0
2015-08-28 11:18:44: WARNING: 404 HEAD /robots.txt (192.168.111.100) 60.86ms
2015-08-28 11:21:28: WARNING: control hue not found for device /dev/video0
2015-08-28 21:59:08: WARNING: control hue not found for device /dev/video0
2015-08-29 10:56:19: WARNING: control hue not found for device /dev/video0
2015-08-29 11:32:35: WARNING: control hue not found for device /dev/video0
2015-08-29 12:14:10: WARNING: control hue not found for device /dev/video0
2015-08-29 12:14:24: WARNING: control hue not found for device /dev/video0
2015-08-29 13:05:15: WARNING: control hue not found for device /dev/video0
2015-08-29 13:05:42: WARNING: control hue not found for device /dev/video0
2015-08-29 13:17:53: WARNING: control hue not found for device /dev/video0
2015-08-29 13:21:30: INFO: adding new camera with id 2...
2015-08-29 13:21:30: WARNING: control hue not found for device /dev/video0
2015-08-29 13:22:35: WARNING: control hue not found for device /dev/video0
2015-08-29 13:23:09: ERROR: failed to list remote cameras on http://192.168.111.60: authentication failed
2015-08-29 13:23:19: INFO: adding new camera with id 3...
2015-08-29 13:23:19: ERROR: expected string or buffer
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1489, in wrapper
  File "/programs/motioneye/src/handlers.py", line 194, in post
    self.add_camera()
  File "/programs/motioneye/src/handlers.py", line 121, in wrapper
    return func(self, *args, **kwargs)
  File "/programs/motioneye/src/handlers.py", line 642, in add_camera
    remote.get_config(camera_config, on_response)
  File "/programs/motioneye/src/remote.py", line 158, in get_config
    request = _make_request(scheme, host, port, username, password, uri + '/config/%(id)s/get/' % {'id': camera_id})
  File "/programs/motioneye/src/remote.py", line 50, in _make_request
    url += '&_signature=' + utils.compute_signature(method, url, data, password)
  File "/programs/motioneye/src/utils.py", line 396, in compute_signature
    key = _SIGNATURE_REGEX.sub('-', key)
TypeError: expected string or buffer
2015-08-29 13:23:19: ERROR: 500 POST /config/add/?_=1440854599801&_username=admin&_signature=10cd5fd5b8801b37781151c91476e70b8f14f622 (192.168.111.100) 74.06ms
2015-08-29 13:24:27: ERROR: failed to list remote cameras on http://192.168.111.60: authentication failed
2015-08-29 13:24:34: INFO: adding new camera with id 4...
2015-08-29 13:24:34: ERROR: expected string or buffer
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1489, in wrapper
  File "/programs/motioneye/src/handlers.py", line 194, in post
    self.add_camera()
  File "/programs/motioneye/src/handlers.py", line 121, in wrapper
    return func(self, *args, **kwargs)
  File "/programs/motioneye/src/handlers.py", line 642, in add_camera
    remote.get_config(camera_config, on_response)
  File "/programs/motioneye/src/remote.py", line 158, in get_config
    request = _make_request(scheme, host, port, username, password, uri + '/config/%(id)s/get/' % {'id': camera_id})
  File "/programs/motioneye/src/remote.py", line 50, in _make_request
    url += '&_signature=' + utils.compute_signature(method, url, data, password)
  File "/programs/motioneye/src/utils.py", line 396, in compute_signature
    key = _SIGNATURE_REGEX.sub('-', key)
TypeError: expected string or buffer
2015-08-29 13:24:34: ERROR: 500 POST /config/add/?_=1440854674518&_username=admin&_signature=57cbd7833605eec052d85708f93a186430267dbd (192.168.111.100) 120.42ms
2015-08-29 13:26:16: ERROR: failed to list remote cameras on http://192.168.111.60: authentication failed
2015-08-29 13:26:24: INFO: adding new camera with id 5...
2015-08-29 13:26:24: ERROR: expected string or buffer
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1489, in wrapper
  File "/programs/motioneye/src/handlers.py", line 194, in post
    self.add_camera()
  File "/programs/motioneye/src/handlers.py", line 121, in wrapper
    return func(self, *args, **kwargs)
  File "/programs/motioneye/src/handlers.py", line 642, in add_camera
    remote.get_config(camera_config, on_response)
  File "/programs/motioneye/src/remote.py", line 158, in get_config
    request = _make_request(scheme, host, port, username, password, uri + '/config/%(id)s/get/' % {'id': camera_id})
  File "/programs/motioneye/src/remote.py", line 50, in _make_request
    url += '&_signature=' + utils.compute_signature(method, url, data, password)
  File "/programs/motioneye/src/utils.py", line 396, in compute_signature
    key = _SIGNATURE_REGEX.sub('-', key)
TypeError: expected string or buffer
2015-08-29 13:26:24: ERROR: 500 POST /config/add/?_=1440854784335&_username=admin&_signature=55de98ff7818350e9e0de447623e98e01ea8319d (192.168.111.100) 57.86ms
2015-08-29 13:41:18: ERROR: failed to list remote cameras on http://192.168.111.60: authentication failed
2015-08-29 13:41:25: INFO: adding new camera with id 6...
2015-08-29 13:41:25: ERROR: expected string or buffer
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1489, in wrapper
  File "/programs/motioneye/src/handlers.py", line 194, in post
    self.add_camera()
  File "/programs/motioneye/src/handlers.py", line 121, in wrapper
    return func(self, *args, **kwargs)
  File "/programs/motioneye/src/handlers.py", line 642, in add_camera
    remote.get_config(camera_config, on_response)
  File "/programs/motioneye/src/remote.py", line 158, in get_config
    request = _make_request(scheme, host, port, username, password, uri + '/config/%(id)s/get/' % {'id': camera_id})
  File "/programs/motioneye/src/remote.py", line 50, in _make_request
    url += '&_signature=' + utils.compute_signature(method, url, data, password)
  File "/programs/motioneye/src/utils.py", line 396, in compute_signature
    key = _SIGNATURE_REGEX.sub('-', key)
TypeError: expected string or buffer
2015-08-29 13:41:25: ERROR: 500 POST /config/add/?_=1440855684897&_username=admin&_signature=ed16fd46edd416c88988eb15a9b5d16ab1440f88 (192.168.111.100) 116.46ms
2015-08-29 13:47:46: ERROR: failed to get current picture for remote camera 1 on http://192.168.111.62/config/1: request timed out
2015-08-29 13:48:17: ERROR: failed to get current picture for remote camera 1 on http://192.168.111.62/config/1: request timed out
2015-08-29 15:19:15: ERROR: failed to get current picture for remote camera 1 on http://192.168.111.62/config/1: request timed out
2015-08-29 18:56:55: WARNING: control hue not found for device /dev/video0
2015-08-29 18:57:48: ERROR: failed to list remote cameras on http://192.168.111.60: authentication failed
2015-08-29 18:57:56: INFO: adding new camera with id 7...
2015-08-29 18:57:56: ERROR: expected string or buffer
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1489, in wrapper
  File "/programs/motioneye/src/handlers.py", line 194, in post
    self.add_camera()
  File "/programs/motioneye/src/handlers.py", line 121, in wrapper
    return func(self, *args, **kwargs)
  File "/programs/motioneye/src/handlers.py", line 642, in add_camera
    remote.get_config(camera_config, on_response)
  File "/programs/motioneye/src/remote.py", line 158, in get_config
    request = _make_request(scheme, host, port, username, password, uri + '/config/%(id)s/get/' % {'id': camera_id})
  File "/programs/motioneye/src/remote.py", line 50, in _make_request
    url += '&_signature=' + utils.compute_signature(method, url, data, password)
  File "/programs/motioneye/src/utils.py", line 396, in compute_signature
    key = _SIGNATURE_REGEX.sub('-', key)
TypeError: expected string or buffer
2015-08-29 18:57:56: ERROR: 500 POST /config/add/?_=1440874676509&_username=admin&_signature=4877aba5022b3c36c551428ca8716525e5387cf1 (192.168.111.100) 104.84ms
2015-08-29 20:38:56: INFO: adding new camera with id 8...
2015-08-29 20:38:57: WARNING: control hue not found for device /dev/video0
2015-08-29 20:38:57: ERROR: expected string or buffer
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1489, in wrapper
  File "/programs/motioneye/src/handlers.py", line 174, in get
    self.list()
  File "/programs/motioneye/src/handlers.py", line 121, in wrapper
    return func(self, *args, **kwargs)
  File "/programs/motioneye/src/handlers.py", line 589, in list
    remote.get_config(local_config, on_response_builder(camera_id, local_config))
  File "/programs/motioneye/src/remote.py", line 158, in get_config
    request = _make_request(scheme, host, port, username, password, uri + '/config/%(id)s/get/' % {'id': camera_id})
  File "/programs/motioneye/src/remote.py", line 50, in _make_request
    url += '&_signature=' + utils.compute_signature(method, url, data, password)
  File "/programs/motioneye/src/utils.py", line 396, in compute_signature
    key = _SIGNATURE_REGEX.sub('-', key)
TypeError: expected string or buffer
2015-08-29 20:38:57: ERROR: 500 GET /config/list/?_=1440880737665&_username=admin&_signature=8283483aec70b3dfbdf59dfe633d89a8227166ab (192.168.111.100) 384.10ms
2015-08-29 20:39:10: WARNING: control hue not found for device /dev/video0
2015-08-29 20:39:10: ERROR: expected string or buffer
Traceback (most recent call last):
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1302, in _stack_context_handle_exception
  File "home/ccrisan/motionpie/output/raspberrypi/target/usr/lib/python2.7/site-packages/tornado/web.py", line 1489, in wrapper
  File "/programs/motioneye/src/handlers.py", line 174, in get
    self.list()
  File "/programs/motioneye/src/handlers.py", line 121, in wrapper
    return func(self, *args, **kwargs)
  File "/programs/motioneye/src/handlers.py", line 589, in list
    remote.get_config(local_config, on_response_builder(camera_id, local_config))
  File "/programs/motioneye/src/remote.py", line 158, in get_config
    request = _make_request(scheme, host, port, username, password, uri + '/config/%(id)s/get/' % {'id': camera_id})
  File "/programs/motioneye/src/remote.py", line 50, in _make_request
    url += '&_signature=' + utils.compute_signature(method, url, data, password)
  File "/programs/motioneye/src/utils.py", line 396, in compute_signature
    key = _SIGNATURE_REGEX.sub('-', key)
TypeError: expected string or buffer
2015-08-29 20:39:10: ERROR: 500 GET /config/list/?_=1440880751078&_username=admin&_signature=cc91b4974f53bf37083a554e9350c3a78774ba30 (192.168.111.100) 76.29ms

**Comment by ccrisan** [comment]
I need a clear explanation of what you did and what the problem was. Also, please send me the log files using online services like those indicated [here](https://github.com/ccrisan/motionpie/wiki/Reporting-An-Issue) rather than pasting everything in the issue content.

**Comment by drknstrmyknight** [comment]
I just went to the ADD A CAMERA, selected remote MotionEye canera, put in HTTP://xxx.xxx.xxx.xxx, and poof, no cameras, plus I couldn't add the local camera back.

**Comment by ccrisan** [comment]
Where did you select "remote MotionEye camera"? On what device? Do you run more than one motionPie-based devices? Do you have a PC running motionEye and trying to add your motionPie-based device to the PC? Please explain the entire scenario so I can understand what you were trying to do.

**Comment by drknstrmyknight** [comment]
I have 3 Rasberry PI's running MotionPIOne one of these. when a try to add one of the other two as a remote MotionEye camera, it blows out the local camera as well as not adding the remote.Maybe using MotionEye as a place to view them all is the answer

**Comment by ccrisan** [comment]
Well you should be able to add one motionPie to another one as motionEye, just as you seem to have tried. I will try to see if there's a problem with this scenario. Do all your motionPie devices run the same version, by the way?

Nevertheless, the correct solution is to configure a separate motionEye server used to centralize all of your devices.

**Comment by drknstrmyknight** [comment]
They have have the latest version of MotionPI, all B+ with Raspberry Pi cams.Setting up MotionEye now, but ran into a snag as the motioneye.py file dated today is empty

**Comment by ccrisan** [comment]
As I commented on the issue you just opened on motionEye, please stick to the bitbucket 0.26 version for now.

**Comment by drknstrmyknight** [comment]
Did that and all is well, you can close this
